#############################################################################
# Makefile for building: Groove
# Generated by qmake (2.01a) (Qt 4.7.3) on: ?? 11? 22 09:26:27 2011
# Project:  Groove.pro
# Template: app
# Command: /home/akaedu/QtSDK/Desktop/Qt/473/gcc/bin/qmake -o Makefile Groove.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_SQL_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I../../QtSDK/Desktop/Qt/473/gcc/mkspecs/default -I. -I../../QtSDK/Desktop/Qt/473/gcc/include/QtCore -I../../QtSDK/Desktop/Qt/473/gcc/include/QtNetwork -I../../QtSDK/Desktop/Qt/473/gcc/include/QtGui -I../../QtSDK/Desktop/Qt/473/gcc/include/QtSql -I../../QtSDK/Desktop/Qt/473/gcc/include -I. -I.
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-rpath,/home/akaedu/QtSDK/Desktop/Qt/473/gcc/lib
LIBS          = $(SUBLIBS)  -L/home/akaedu/QtSDK/Desktop/Qt/473/gcc/lib -lQtSql -lQtGui -lQtNetwork -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /home/akaedu/QtSDK/Desktop/Qt/473/gcc/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		comm.cpp \
		sendmessage.cpp \
		workspace.cpp \
		tip.cpp \
		message.cpp \
		ipinfo.cpp \
		iplist.cpp \
		commserver.cpp \
		login.cpp \
		gsession.cpp \
		gregister.cpp moc_comm.cpp \
		moc_sendmessage.cpp \
		moc_workspace.cpp \
		moc_tip.cpp \
		moc_message.cpp \
		moc_commserver.cpp \
		moc_login.cpp \
		moc_gregister.cpp \
		qrc_rs.cpp
OBJECTS       = main.o \
		comm.o \
		sendmessage.o \
		workspace.o \
		tip.o \
		message.o \
		ipinfo.o \
		iplist.o \
		commserver.o \
		login.o \
		gsession.o \
		gregister.o \
		moc_comm.o \
		moc_sendmessage.o \
		moc_workspace.o \
		moc_tip.o \
		moc_message.o \
		moc_commserver.o \
		moc_login.o \
		moc_gregister.o \
		qrc_rs.o
DIST          = ../../QtSDK/Desktop/Qt/473/gcc/mkspecs/common/g++.conf \
		../../QtSDK/Desktop/Qt/473/gcc/mkspecs/common/unix.conf \
		../../QtSDK/Desktop/Qt/473/gcc/mkspecs/common/linux.conf \
		../../QtSDK/Desktop/Qt/473/gcc/mkspecs/qconfig.pri \
		../../QtSDK/Desktop/Qt/473/gcc/mkspecs/modules/qt_webkit_version.pri \
		../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/qt_functions.prf \
		../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/qt_config.prf \
		../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/exclusive_builds.prf \
		../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/default_pre.prf \
		../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/release.prf \
		../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/default_post.prf \
		../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/warn_on.prf \
		../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/qt.prf \
		../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/unix/thread.prf \
		../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/moc.prf \
		../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/resources.prf \
		../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/uic.prf \
		../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/yacc.prf \
		../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/lex.prf \
		../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/include_source_dir.prf \
		Groove.pro
QMAKE_TARGET  = Groove
DESTDIR       = 
TARGET        = Groove

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_comm.h ui_sendmessage.h ui_workspace.h ui_tip.h ui_message.h ui_login.h ui_gregister.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Groove.pro  ../../QtSDK/Desktop/Qt/473/gcc/mkspecs/default/qmake.conf ../../QtSDK/Desktop/Qt/473/gcc/mkspecs/common/g++.conf \
		../../QtSDK/Desktop/Qt/473/gcc/mkspecs/common/unix.conf \
		../../QtSDK/Desktop/Qt/473/gcc/mkspecs/common/linux.conf \
		../../QtSDK/Desktop/Qt/473/gcc/mkspecs/qconfig.pri \
		../../QtSDK/Desktop/Qt/473/gcc/mkspecs/modules/qt_webkit_version.pri \
		../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/qt_functions.prf \
		../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/qt_config.prf \
		../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/exclusive_builds.prf \
		../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/default_pre.prf \
		../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/release.prf \
		../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/default_post.prf \
		../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/warn_on.prf \
		../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/qt.prf \
		../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/unix/thread.prf \
		../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/moc.prf \
		../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/resources.prf \
		../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/uic.prf \
		../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/yacc.prf \
		../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/lex.prf \
		../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/include_source_dir.prf
	$(QMAKE) -o Makefile Groove.pro
../../QtSDK/Desktop/Qt/473/gcc/mkspecs/common/g++.conf:
../../QtSDK/Desktop/Qt/473/gcc/mkspecs/common/unix.conf:
../../QtSDK/Desktop/Qt/473/gcc/mkspecs/common/linux.conf:
../../QtSDK/Desktop/Qt/473/gcc/mkspecs/qconfig.pri:
../../QtSDK/Desktop/Qt/473/gcc/mkspecs/modules/qt_webkit_version.pri:
../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/qt_functions.prf:
../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/qt_config.prf:
../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/exclusive_builds.prf:
../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/default_pre.prf:
../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/release.prf:
../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/default_post.prf:
../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/warn_on.prf:
../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/qt.prf:
../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/unix/thread.prf:
../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/moc.prf:
../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/resources.prf:
../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/uic.prf:
../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/yacc.prf:
../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/lex.prf:
../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/include_source_dir.prf:
qmake:  FORCE
	@$(QMAKE) -o Makefile Groove.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/Groove1.0.0 || $(MKDIR) .tmp/Groove1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/Groove1.0.0/ && $(COPY_FILE) --parents comm.h sendmessage.h workspace.h tip.h message.h ipinfo.h iplist.h commserver.h login.h gsession.h gregister.h .tmp/Groove1.0.0/ && $(COPY_FILE) --parents rs.qrc .tmp/Groove1.0.0/ && $(COPY_FILE) --parents main.cpp comm.cpp sendmessage.cpp workspace.cpp tip.cpp message.cpp ipinfo.cpp iplist.cpp commserver.cpp login.cpp gsession.cpp gregister.cpp .tmp/Groove1.0.0/ && $(COPY_FILE) --parents comm.ui sendmessage.ui workspace.ui tip.ui message.ui login.ui gregister.ui .tmp/Groove1.0.0/ && (cd `dirname .tmp/Groove1.0.0` && $(TAR) Groove1.0.0.tar Groove1.0.0 && $(COMPRESS) Groove1.0.0.tar) && $(MOVE) `dirname .tmp/Groove1.0.0`/Groove1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/Groove1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_comm.cpp moc_sendmessage.cpp moc_workspace.cpp moc_tip.cpp moc_message.cpp moc_commserver.cpp moc_login.cpp moc_gregister.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_comm.cpp moc_sendmessage.cpp moc_workspace.cpp moc_tip.cpp moc_message.cpp moc_commserver.cpp moc_login.cpp moc_gregister.cpp
moc_comm.cpp: comm.h
	/home/akaedu/QtSDK/Desktop/Qt/473/gcc/bin/moc $(DEFINES) $(INCPATH) comm.h -o moc_comm.cpp

moc_sendmessage.cpp: gsession.h \
		sendmessage.h
	/home/akaedu/QtSDK/Desktop/Qt/473/gcc/bin/moc $(DEFINES) $(INCPATH) sendmessage.h -o moc_sendmessage.cpp

moc_workspace.cpp: workspace.h
	/home/akaedu/QtSDK/Desktop/Qt/473/gcc/bin/moc $(DEFINES) $(INCPATH) workspace.h -o moc_workspace.cpp

moc_tip.cpp: tip.h
	/home/akaedu/QtSDK/Desktop/Qt/473/gcc/bin/moc $(DEFINES) $(INCPATH) tip.h -o moc_tip.cpp

moc_message.cpp: gsession.h \
		commserver.h \
		message.h
	/home/akaedu/QtSDK/Desktop/Qt/473/gcc/bin/moc $(DEFINES) $(INCPATH) message.h -o moc_message.cpp

moc_commserver.cpp: commserver.h
	/home/akaedu/QtSDK/Desktop/Qt/473/gcc/bin/moc $(DEFINES) $(INCPATH) commserver.h -o moc_commserver.cpp

moc_login.cpp: gsession.h \
		login.h
	/home/akaedu/QtSDK/Desktop/Qt/473/gcc/bin/moc $(DEFINES) $(INCPATH) login.h -o moc_login.cpp

moc_gregister.cpp: gsession.h \
		gregister.h
	/home/akaedu/QtSDK/Desktop/Qt/473/gcc/bin/moc $(DEFINES) $(INCPATH) gregister.h -o moc_gregister.cpp

compiler_rcc_make_all: qrc_rs.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_rs.cpp
qrc_rs.cpp: rs.qrc \
		image/Files.png \
		image/E-Mail.png \
		image/MSN-Messenger.png \
		image/smbk4.png \
		image/loginbk.png \
		image/textunder.png \
		image/User.png \
		image/fileopen.png \
		image/smbk5.png \
		image/Floppy.png \
		image/textcolor.png \
		image/loginbk1.png \
		image/loginbk2.jpg \
		image/textitalic.png \
		image/smbk.jpg \
		image/textbold.png \
		image/smbk3.png
	/home/akaedu/QtSDK/Desktop/Qt/473/gcc/bin/rcc -name rs rs.qrc -o qrc_rs.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_comm.h ui_sendmessage.h ui_workspace.h ui_tip.h ui_message.h ui_login.h ui_gregister.h
compiler_uic_clean:
	-$(DEL_FILE) ui_comm.h ui_sendmessage.h ui_workspace.h ui_tip.h ui_message.h ui_login.h ui_gregister.h
ui_comm.h: comm.ui
	/home/akaedu/QtSDK/Desktop/Qt/473/gcc/bin/uic comm.ui -o ui_comm.h

ui_sendmessage.h: sendmessage.ui
	/home/akaedu/QtSDK/Desktop/Qt/473/gcc/bin/uic sendmessage.ui -o ui_sendmessage.h

ui_workspace.h: workspace.ui
	/home/akaedu/QtSDK/Desktop/Qt/473/gcc/bin/uic workspace.ui -o ui_workspace.h

ui_tip.h: tip.ui
	/home/akaedu/QtSDK/Desktop/Qt/473/gcc/bin/uic tip.ui -o ui_tip.h

ui_message.h: message.ui
	/home/akaedu/QtSDK/Desktop/Qt/473/gcc/bin/uic message.ui -o ui_message.h

ui_login.h: login.ui
	/home/akaedu/QtSDK/Desktop/Qt/473/gcc/bin/uic login.ui -o ui_login.h

ui_gregister.h: gregister.ui
	/home/akaedu/QtSDK/Desktop/Qt/473/gcc/bin/uic gregister.ui -o ui_gregister.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

main.o: main.cpp comm.h \
		commserver.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

comm.o: comm.cpp comm.h \
		sendmessage.h \
		gsession.h \
		commserver.h \
		ui_comm.h \
		login.h \
		gregister.h \
		message.h \
		ui_message.h \
		tip.h \
		ui_tip.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o comm.o comm.cpp

sendmessage.o: sendmessage.cpp sendmessage.h \
		gsession.h \
		message.h \
		commserver.h \
		workspace.h \
		ui_sendmessage.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sendmessage.o sendmessage.cpp

workspace.o: workspace.cpp workspace.h \
		ui_workspace.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o workspace.o workspace.cpp

tip.o: tip.cpp tip.h \
		ui_tip.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tip.o tip.cpp

message.o: message.cpp message.h \
		gsession.h \
		commserver.h \
		ui_message.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o message.o message.cpp

ipinfo.o: ipinfo.cpp ipinfo.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ipinfo.o ipinfo.cpp

iplist.o: iplist.cpp iplist.h \
		ipinfo.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o iplist.o iplist.cpp

commserver.o: commserver.cpp commserver.h \
		message.h \
		gsession.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o commserver.o commserver.cpp

login.o: login.cpp login.h \
		gsession.h \
		ui_login.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o login.o login.cpp

gsession.o: gsession.cpp gsession.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o gsession.o gsession.cpp

gregister.o: gregister.cpp gregister.h \
		gsession.h \
		ui_gregister.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o gregister.o gregister.cpp

moc_comm.o: moc_comm.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_comm.o moc_comm.cpp

moc_sendmessage.o: moc_sendmessage.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_sendmessage.o moc_sendmessage.cpp

moc_workspace.o: moc_workspace.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_workspace.o moc_workspace.cpp

moc_tip.o: moc_tip.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_tip.o moc_tip.cpp

moc_message.o: moc_message.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_message.o moc_message.cpp

moc_commserver.o: moc_commserver.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_commserver.o moc_commserver.cpp

moc_login.o: moc_login.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_login.o moc_login.cpp

moc_gregister.o: moc_gregister.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_gregister.o moc_gregister.cpp

qrc_rs.o: qrc_rs.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_rs.o qrc_rs.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

